name: 'Slack Lookup By Email'
description: 'Find a Slack user by their email address'
author: 'danielbowden'
branding:
  icon: user
  color: blue
inputs:
  email:
    required: true
    description: "user's email address to query"
outputs:
  user:
    description: 'The user profile hash as defined in https://api.slack.com/methods/users.lookupByEmail#profile'
runs:
  using: 'node16'
  main: 'dist/index.js'
